/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels.contentBodys.desktop;

import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.impl.BodyType;

import javax.swing.*;

/**
 *
 * @author plocki
 */
public class LoginBody extends BodyType {

    /**
     * Creates new form LoginBody
     */
    public LoginBody() {
        initComponents();

        addTextField("username_textfield", username_textfield);
        addTextField("password_textfield", password_textfield);
        addLabel("login_title", login_title);
        addLabel("action_label", action_label);
        addButton("confirm_button", confirm_button);
    }

    @Override
    public JLabel getActionLabel() {
        return action_label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overlayPanel = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        password_textfield = new javax.swing.JPasswordField();
        username_textfield = new javax.swing.JTextField();
        confirm_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        action_label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 21, 28));
        setForeground(new java.awt.Color(231, 231, 231));
        setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1218, 1012));
        setSize(new java.awt.Dimension(1218, 1012));

        overlayPanel.setBackground(new java.awt.Color(231, 231, 231));

        login_title.setFont(new java.awt.Font("Oswald", 0, 48)); // NOI18N
        login_title.setText("Login");

        password_textfield.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        password_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_textfield.setToolTipText("Passwort");

        username_textfield.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        username_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_textfield.setToolTipText("Nutzername");

        confirm_button.setBackground(new java.awt.Color(30, 150, 252));
        confirm_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        confirm_button.setForeground(new java.awt.Color(231, 231, 231));
        confirm_button.setText("Anmelden");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alle Informationen die durch diese Applikation übermittelt werden sind SSL verschlüsselt.");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informationen welche durch diese Applikationen freigegeben werden sind strengst vertraulich und geheimzuhalten.");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Die Weiterverarbeitung zu weiteren Zwecken als die Auftragserfüllung im Vertraglich festgelegten Rahmen ist nicht gestattet.");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Support: admin@kabuecher.de | +49-(0)721-61932199");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Durch die Verwendung dieser Applikation entstehen Gebühren gemäß des abgeschlossenen \"KA-DIREKT\"-Plattformvertrages.");

        javax.swing.GroupLayout overlayPanelLayout = new javax.swing.GroupLayout(overlayPanel);
        overlayPanel.setLayout(overlayPanelLayout);
        overlayPanelLayout.setHorizontalGroup(
            overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overlayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overlayPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overlayPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(overlayPanelLayout.createSequentialGroup()
                                .addGroup(overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(overlayPanelLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(262, 262, 262))
                            .addGroup(overlayPanelLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(login_title))))
                    .addGroup(overlayPanelLayout.createSequentialGroup()
                        .addGroup(overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        overlayPanelLayout.setVerticalGroup(
            overlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overlayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(login_title)
                .addGap(18, 18, 18)
                .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        action_label.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        action_label.setForeground(new java.awt.Color(231, 231, 231));
        action_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(action_label, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(overlayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(overlayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(action_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        handleActionEvent("confirm_button", evt);
    }//GEN-LAST:event_confirm_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_label;
    private javax.swing.JButton confirm_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel login_title;
    private javax.swing.JPanel overlayPanel;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
