/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels.contentBodys.desktop;

import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.impl.BodyType;

import javax.swing.*;

/**
 *
 * @author plocki
 */
public class ShipBody extends BodyType {

    /**
     * Creates new form LoginBody
     */
    public ShipBody() {
        initComponents();

        addLabel("action_label", action_label);
        addButton("button_500g", button_500g);
        addButton("button_1kg", button_1kg);
        addButton("button_2kg", button_2kg);
        addButton("button_5kg", button_5kg);
        addButton("button_10kg", button_10kg);
        addButton("button_15kg", button_15kg);
        addButton("button_30kg", button_30kg);
        addButton("button_25kg", button_25kg);

    }

    @Override
    public JLabel getActionLabel() {
        return action_label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button_500g = new javax.swing.JButton();
        button_1kg = new javax.swing.JButton();
        button_2kg = new javax.swing.JButton();
        button_5kg = new javax.swing.JButton();
        button_10kg = new javax.swing.JButton();
        button_15kg = new javax.swing.JButton();
        button_30kg = new javax.swing.JButton();
        button_25kg = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 21, 28));
        setForeground(new java.awt.Color(231, 231, 231));
        setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1218, 1012));
        setSize(new java.awt.Dimension(1218, 1012));

        action_label.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        action_label.setForeground(new java.awt.Color(231, 231, 231));
        action_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 231, 231));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gewicht angeben");

        button_500g.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_500g.setText("<=500g");
        button_500g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_500gActionPerformed(evt);
            }
        });

        button_1kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_1kg.setText("<=1kg");
        button_1kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1kgActionPerformed(evt);
            }
        });

        button_2kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_2kg.setText("<=2kg");
        button_2kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2kgActionPerformed(evt);
            }
        });

        button_5kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_5kg.setText("<=5kg");
        button_5kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5kgActionPerformed(evt);
            }
        });

        button_10kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_10kg.setText("<=10kg");
        button_10kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_10kgActionPerformed(evt);
            }
        });

        button_15kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_15kg.setText("<=15kg");
        button_15kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_15kgActionPerformed(evt);
            }
        });

        button_30kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_30kg.setText("<=30kg");
        button_30kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_30kgActionPerformed(evt);
            }
        });

        button_25kg.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        button_25kg.setText("<=25kg");
        button_25kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_25kgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(action_label, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_1kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_500g, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_2kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_5kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_10kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_15kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_30kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_25kg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_500g, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_10kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_15kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_2kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_25kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_5kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_30kg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(action_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_500gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_500gActionPerformed
        handleActionEvent("button_500g", evt);
    }//GEN-LAST:event_button_500gActionPerformed

    private void button_1kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1kgActionPerformed
        handleActionEvent("button_1kg", evt);
    }//GEN-LAST:event_button_1kgActionPerformed

    private void button_2kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2kgActionPerformed
        handleActionEvent("button_2kg", evt);
    }//GEN-LAST:event_button_2kgActionPerformed

    private void button_5kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5kgActionPerformed
        handleActionEvent("button_5kg", evt);
    }//GEN-LAST:event_button_5kgActionPerformed

    private void button_10kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_10kgActionPerformed
        handleActionEvent("button_10kg", evt);
    }//GEN-LAST:event_button_10kgActionPerformed

    private void button_15kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_15kgActionPerformed
        handleActionEvent("button_15kg", evt);
    }//GEN-LAST:event_button_15kgActionPerformed

    private void button_30kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_30kgActionPerformed
        handleActionEvent("button_30kg", evt);
    }//GEN-LAST:event_button_30kgActionPerformed

    private void button_25kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_25kgActionPerformed
        handleActionEvent("button_25kg", evt);
    }//GEN-LAST:event_button_25kgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action_label;
    private javax.swing.JButton button_10kg;
    private javax.swing.JButton button_15kg;
    private javax.swing.JButton button_1kg;
    private javax.swing.JButton button_25kg;
    private javax.swing.JButton button_2kg;
    private javax.swing.JButton button_30kg;
    private javax.swing.JButton button_500g;
    private javax.swing.JButton button_5kg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
