/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels.contentBodys.desktop.component;

import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.impl.ComponentType;
import de.kabuecher.storage.v4.sevdesk.impl.offer.Offer;

/**
 *
 * @author plocki
 */
public class SummarizingBodyOrderComponent extends ComponentType {

    /**
     * Creates new form SummarizingBodyCartComponent
     */
    public SummarizingBodyOrderComponent(Offer offer) {
        initComponents();

        addLabel("order_number_label", order_number_label);
        order_number_label.setText(offer.getOrderNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        order_number_label = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBounds(new java.awt.Rectangle(680, 90, 680, 90));
        setMaximumSize(new java.awt.Dimension(680, 90));
        setMinimumSize(new java.awt.Dimension(680, 90));
        setPreferredSize(new java.awt.Dimension(680, 90));

        order_number_label.setBackground(new java.awt.Color(231, 231, 231));
        order_number_label.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        order_number_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        order_number_label.setText("order_no");

        submit_button.setBackground(new java.awt.Color(30, 150, 252));
        submit_button.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        submit_button.setForeground(new java.awt.Color(231, 231, 231));
        submit_button.setText("Ausführen");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(order_number_label, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit_button)
                    .addComponent(order_number_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        handleActionEvent("submit_button", evt);
    }//GEN-LAST:event_submit_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel order_number_label;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
