/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels.contentBodys.desktop.component;

import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.impl.ComponentType;
import org.json.JSONObject;

/**
 *
 * @author plocki
 */
public class SummarizingBodyCartComponent extends ComponentType {

    private final JSONObject unitInfo;

    /**
     * Creates new form SummarizingBodyCartComponent
     */
    public SummarizingBodyCartComponent(JSONObject unitInfo, String name, int count) {
        initComponents();
        this.unitInfo = unitInfo;

        addButton("delete_button", delete_button);
        addButton("change_button", change_button);

        art_name_label.setText(name);
        count_label.setText(String.valueOf(count));
    }

    @Override
    public JSONObject getUnitInfo() {
        return unitInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        art_name_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        count_label = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        change_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBounds(new java.awt.Rectangle(680, 90, 680, 90));
        setMaximumSize(new java.awt.Dimension(680, 90));
        setMinimumSize(new java.awt.Dimension(680, 90));
        setPreferredSize(new java.awt.Dimension(680, 90));

        art_name_label.setBackground(new java.awt.Color(231, 231, 231));
        art_name_label.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        art_name_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        art_name_label.setText("art_name");

        jLabel2.setBackground(new java.awt.Color(231, 231, 231));
        jLabel2.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("x");

        count_label.setBackground(new java.awt.Color(231, 231, 231));
        count_label.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        count_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        count_label.setText("0");

        delete_button.setBackground(new java.awt.Color(244, 68, 46));
        delete_button.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        delete_button.setForeground(new java.awt.Color(231, 231, 231));
        delete_button.setText("Löschen");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        change_button.setBackground(new java.awt.Color(30, 150, 252));
        change_button.setFont(new java.awt.Font("Oswald", 0, 18)); // NOI18N
        change_button.setForeground(new java.awt.Color(231, 231, 231));
        change_button.setText("Anzahl Ändern");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(art_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(change_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change_button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(count_label))
                            .addComponent(art_name_label))))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        handleActionEvent("delete_button", evt);
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        handleActionEvent("change_button", evt);
    }//GEN-LAST:event_change_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel art_name_label;
    private javax.swing.JButton change_button;
    private javax.swing.JLabel count_label;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
