/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels;

import de.kabuecher.storage.v4.Main;
import de.kabuecher.storage.v4.client.desktop.DesktopContentBodyHandler;
import de.kabuecher.storage.v4.client.flows.*;
import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.SummarizingBody;
import de.kabuecher.storage.v4.client.panels.contentBodys.desktop.impl.BodyType;
import de.kabuecher.storage.v4.client.utils.storage.UnitManagementClient;
import org.json.JSONObject;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author plocki
 */
public class DesktopMainPanel extends javax.swing.JPanel {

    private final DesktopContentBodyHandler bodyHandler;
    private final JFrame frame;

    /**
     * Creates new form MainPanel
     */
    public DesktopMainPanel(JFrame frame) {

        Main.addToLog("Starting main panel");

        initComponents();
        this.frame = frame;

        bodyHandler = new DesktopContentBodyHandler(frame, contentBody);
        login_logout_button.setEnabled(false);

        Main.addToLog("Main panel started");
    }

    public JButton getLogoutButton() {
        return login_logout_button;
    }

    public JLabel getTimeLabel() {
        return timeLabel;
    }

    public DesktopContentBodyHandler getBodyHandler() {
        return bodyHandler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        sideBar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        hub_outgoing_button = new javax.swing.JButton();
        orders_button = new javax.swing.JButton();
        hub_ingoing_button = new javax.swing.JButton();
        login_logout_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scanField = new javax.swing.JTextField();
        ship_button = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        fullscreenToggle = new javax.swing.JToggleButton();
        timeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        versionLabel1 = new javax.swing.JLabel();
        contentBody = new javax.swing.JPanel();

        setBackground(new java.awt.Color(17, 21, 28));
        setMinimumSize(new java.awt.Dimension(1538, 1024));
        setPreferredSize(new java.awt.Dimension(1538, 1024));
        setSize(new java.awt.Dimension(1538, 1024));

        sideBar.setBackground(new java.awt.Color(33, 35, 64));
        sideBar.setSize(new java.awt.Dimension(264, 1024));

        title.setFont(new java.awt.Font("Oswald", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Lagersystem");
        title.setToolTipText("");

        hub_outgoing_button.setBackground(new java.awt.Color(231, 231, 231));
        hub_outgoing_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        hub_outgoing_button.setText("Lagerausgang");
        hub_outgoing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hub_outgoing_buttonActionPerformed(evt);
            }
        });

        orders_button.setBackground(new java.awt.Color(231, 231, 231));
        orders_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        orders_button.setText("Bestellungen");
        orders_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_buttonActionPerformed(evt);
            }
        });

        hub_ingoing_button.setBackground(new java.awt.Color(231, 231, 231));
        hub_ingoing_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        hub_ingoing_button.setText("Lagereingang");
        hub_ingoing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hub_ingoing_buttonActionPerformed(evt);
            }
        });

        login_logout_button.setBackground(new java.awt.Color(231, 231, 231));
        login_logout_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        login_logout_button.setText("Abmelden");

        jLabel2.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 231, 231));
        jLabel2.setText("- EANs");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 231, 231));
        jLabel3.setText("Folgendes ist scannbar:");

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 231, 231));
        jLabel5.setText("- Boxcodes");

        jLabel6.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 231, 231));
        jLabel6.setText("- Liefercodes");

        scanField.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        scanField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scanField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                scanFieldKeyPressed(evt);
            }
        });

        ship_button.setBackground(new java.awt.Color(231, 231, 231));
        ship_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        ship_button.setText("Versand");
        ship_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ship_buttonActionPerformed(evt);
            }
        });

        versionLabel.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("Copyright 2024-2025 Karlsruher Bücher - Harald Pflug");
        versionLabel.setToolTipText("");

        fullscreenToggle.setText("Vollbild");
        fullscreenToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullscreenToggleActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(231, 231, 231));
        timeLabel.setText("00:00");

        jLabel7.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(231, 231, 231));
        jLabel7.setText("Zeit bis Abmeldung:");

        versionLabel1.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        versionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel1.setText("V4.2");
        versionLabel1.setToolTipText("");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scanField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hub_outgoing_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hub_ingoing_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orders_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ship_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(sideBarLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addGroup(sideBarLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fullscreenToggle))))
                                .addGroup(sideBarLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(timeLabel)))))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(versionLabel1)))
                .addContainerGap())
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(versionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orders_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hub_ingoing_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hub_outgoing_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ship_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fullscreenToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scanField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(login_logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addGap(10, 10, 10))
        );

        contentBody.setBackground(new java.awt.Color(17, 21, 28));
        contentBody.setSize(new java.awt.Dimension(1218, 1012));

        javax.swing.GroupLayout contentBodyLayout = new javax.swing.GroupLayout(contentBody);
        contentBody.setLayout(contentBodyLayout);
        contentBodyLayout.setHorizontalGroup(
            contentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1236, Short.MAX_VALUE)
        );
        contentBodyLayout.setVerticalGroup(
            contentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(sideBar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(contentBody, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hub_outgoing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hub_outgoing_buttonActionPerformed
        new OutgoingInventoryFlow();
    }//GEN-LAST:event_hub_outgoing_buttonActionPerformed

    private void hub_ingoing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hub_ingoing_buttonActionPerformed
        new IngoingInventoryFlow();
    }//GEN-LAST:event_hub_ingoing_buttonActionPerformed

    private void ship_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ship_buttonActionPerformed
        new ShipFlow();
    }//GEN-LAST:event_ship_buttonActionPerformed

    private void orders_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_buttonActionPerformed
        new OrderViewFlow();
    }//GEN-LAST:event_orders_buttonActionPerformed

    private void fullscreenToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullscreenToggleActionPerformed
        if(frame.getExtendedState() == JFrame.NORMAL) {
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setUndecorated(true);
            Main.addToLog("Fullscreen enabled");
        } else {
            frame.setExtendedState(JFrame.NORMAL);
            frame.setUndecorated(false);
            Main.addToLog("Fullscreen disabled");
        }
    }//GEN-LAST:event_fullscreenToggleActionPerformed

    private void scanFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scanFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(scanField.getText().startsWith("LEF")) {
                new ShipFlow().analyzeScan(scanField.getText());
            } else if(scanField.getText().startsWith("BX")) {

                UnitManagementClient unitManagement = new UnitManagementClient();
                JSONObject object = unitManagement.getStoredItems(Main.username);

                boolean breakOuter = false;

                for (String stack : object.getJSONObject(Main.username).getJSONObject("stacks").keySet()) {
                    JSONObject stackObject = object.getJSONObject(Main.username).getJSONObject("stacks").getJSONObject(stack);
                    for (String box : stackObject.keySet()) {
                        if (box.equals(scanField.getText())) {
                            object.getJSONObject(Main.username).getJSONObject("stacks").put(stack, new JSONObject().put(box, stackObject.getJSONObject(box)));
                            breakOuter = true;
                            break;
                        }
                    }
                    if(breakOuter) {
                        break;
                    }
                }

                SummarizingBody body = new SummarizingBody(object, false, true);

                body.getButton("confirm_button").setEnabled(false);
                body.addAction("cancel_button", new BodyType.ActionEventRunnable() {
                    @Override
                    public void handleActionEvent(ActionEvent event) {
                        bodyHandler.setContentBody(null);
                    }

                    @Override
                    public void handleKeyEvent(KeyEvent event) {

                    }

                    @Override
                    public void run() {

                    }
                });

                scanField.setText("");
                bodyHandler.setContentBody(body);
            } else if(scanField.getText().length() == 12 || scanField.getText().length() == 13) {
                for(int i = 0; i < scanField.getText().length(); i++) {
                    if(!Character.isDigit(scanField.getText().charAt(i))) {
                        scanField.setText("");
                    } else {

                        int totalAmount = 0;

                        JSONObject units = new JSONObject().put(Main.username, new JSONObject().put("stacks", new JSONObject()));

                        UnitManagementClient unitManagement = new UnitManagementClient();
                        JSONObject object = unitManagement.getStoredItems(Main.username);
                        for (String stack : object.getJSONObject(Main.username).getJSONObject("stacks").keySet()) {
                            JSONObject stackObject = object.getJSONObject(Main.username).getJSONObject("stacks").getJSONObject(stack);
                            for (String box : stackObject.keySet()) {
                                JSONObject boxObject = stackObject.getJSONObject(box);
                                for (String item : boxObject.keySet()) {
                                    if (item.equals(scanField.getText())) {
                                        if (!units.getJSONObject(Main.username).getJSONObject("stacks").has(stack)) {
                                            units.getJSONObject(Main.username).getJSONObject("stacks").put(stack, new JSONObject());
                                        }
                                        JSONObject stackObj = units.getJSONObject(Main.username).getJSONObject("stacks").getJSONObject(stack);
                                        if (!stackObj.has(box)) {
                                            stackObj.put(box, new JSONObject());
                                        }
                                        JSONObject boxObj = stackObj.getJSONObject(box);
                                        boxObj.put(item, boxObj.optInt(item, 0) + boxObject.getInt(item));
                                        totalAmount += boxObject.getInt(item);
                                    }
                                }
                            }
                        }

                        object = units;

                        SummarizingBody body = new SummarizingBody(object, false, true);

                        body.getButton("confirm_button").setEnabled(false);
                        body.addAction("cancel_button", new BodyType.ActionEventRunnable() {
                            @Override
                            public void handleActionEvent(ActionEvent event) {
                                bodyHandler.setContentBody(null);
                            }

                            @Override
                            public void handleKeyEvent(KeyEvent event) {

                            }

                            @Override
                            public void run() {

                            }
                        });

                        scanField.setText("");
                        body.getActionLabel().setText("Gesamtmenge: " + totalAmount);
                        bodyHandler.setContentBody(body);
                    }
                }
            }
        }
    }//GEN-LAST:event_scanFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentBody;
    private javax.swing.JToggleButton fullscreenToggle;
    private javax.swing.JButton hub_ingoing_button;
    private javax.swing.JButton hub_outgoing_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton login_logout_button;
    private javax.swing.JButton orders_button;
    private javax.swing.JTextField scanField;
    private javax.swing.JButton ship_button;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionLabel1;
    // End of variables declaration//GEN-END:variables
}
