/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.kabuecher.storage.v4.client.panels;

import de.kabuecher.storage.v4.Main;
import de.kabuecher.storage.v4.client.desktop.DesktopContentBodyHandler;
import de.kabuecher.storage.v4.client.flows.IngoingInventoryFlow;
import de.kabuecher.storage.v4.client.flows.OrderViewFlow;
import de.kabuecher.storage.v4.client.flows.OutgoingInventoryFlow;

import javax.swing.*;

/**
 *
 * @author plocki
 */
public class DesktopMainPanel extends javax.swing.JPanel {

    private final DesktopContentBodyHandler bodyHandler;

    /**
     * Creates new form MainPanel
     */
    public DesktopMainPanel(JFrame frame) {
        initComponents();

        bodyHandler = new DesktopContentBodyHandler(frame, contentBody);
    }

    public DesktopContentBodyHandler getBodyHandler() {
        return bodyHandler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        sideBar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        hub_outgoing_button = new javax.swing.JButton();
        orders_button = new javax.swing.JButton();
        hub_ingoing_button = new javax.swing.JButton();
        login_logout_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scanField = new javax.swing.JTextField();
        ship_button = new javax.swing.JButton();
        contentBody = new javax.swing.JPanel();

        setBackground(new java.awt.Color(17, 21, 28));
        setMinimumSize(new java.awt.Dimension(1538, 1024));
        setPreferredSize(new java.awt.Dimension(1538, 1024));
        setSize(new java.awt.Dimension(1538, 1024));

        sideBar.setBackground(new java.awt.Color(33, 35, 64));
        sideBar.setSize(new java.awt.Dimension(264, 1024));

        title.setFont(new java.awt.Font("Oswald", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Lagersystem V4");
        title.setToolTipText("");

        hub_outgoing_button.setBackground(new java.awt.Color(231, 231, 231));
        hub_outgoing_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        hub_outgoing_button.setText("Lagerausgang");
        hub_outgoing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hub_outgoing_buttonActionPerformed(evt);
            }
        });

        orders_button.setBackground(new java.awt.Color(231, 231, 231));
        orders_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        orders_button.setText("Bestellungen");
        orders_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_buttonActionPerformed(evt);
            }
        });

        hub_ingoing_button.setBackground(new java.awt.Color(231, 231, 231));
        hub_ingoing_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        hub_ingoing_button.setText("Lagereingang");
        hub_ingoing_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hub_ingoing_buttonActionPerformed(evt);
            }
        });

        login_logout_button.setBackground(new java.awt.Color(231, 231, 231));
        login_logout_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        login_logout_button.setText("Anmelden / Abmelden");

        jLabel2.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 231, 231));
        jLabel2.setText("- EANs");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 231, 231));
        jLabel3.setText("Folgendes ist scannbar:");

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 231, 231));
        jLabel4.setText("- Leitcodes");

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 231, 231));
        jLabel5.setText("- Boxcodes");

        jLabel6.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 231, 231));
        jLabel6.setText("- Versandcodes");

        scanField.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        scanField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ship_button.setBackground(new java.awt.Color(231, 231, 231));
        ship_button.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        ship_button.setText("Versand");
        ship_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ship_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scanField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hub_outgoing_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hub_ingoing_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orders_button, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(login_logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ship_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orders_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hub_ingoing_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hub_outgoing_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ship_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(scanField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contentBody.setBackground(new java.awt.Color(17, 21, 28));
        contentBody.setSize(new java.awt.Dimension(1218, 1012));

        javax.swing.GroupLayout contentBodyLayout = new javax.swing.GroupLayout(contentBody);
        contentBody.setLayout(contentBodyLayout);
        contentBodyLayout.setHorizontalGroup(
            contentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        contentBodyLayout.setVerticalGroup(
            contentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(sideBar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(contentBody, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hub_outgoing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hub_outgoing_buttonActionPerformed
        new OutgoingInventoryFlow();
    }//GEN-LAST:event_hub_outgoing_buttonActionPerformed

    private void hub_ingoing_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hub_ingoing_buttonActionPerformed
        new IngoingInventoryFlow();
    }//GEN-LAST:event_hub_ingoing_buttonActionPerformed

    private void ship_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ship_buttonActionPerformed
        Main.bodyHandler.setContentBody(null);
    }//GEN-LAST:event_ship_buttonActionPerformed

    private void orders_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_buttonActionPerformed
        new OrderViewFlow();
    }//GEN-LAST:event_orders_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentBody;
    private javax.swing.JButton hub_ingoing_button;
    private javax.swing.JButton hub_outgoing_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton login_logout_button;
    private javax.swing.JButton orders_button;
    private javax.swing.JTextField scanField;
    private javax.swing.JButton ship_button;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
